version: '2'

services:

  wordpress:
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    ports:
      - 18080:18080
    links:
      - db:db
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      WP_ENV: development
      WP_HOME: http://localhost:18080
      WP_SITEURL: http://localhost:18080/wp

  db:
   image: mysql:5.7.18
   ports:
     - 13306:3306
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress

  phpmyadmin:
   image: phpmyadmin/phpmyadmin:4.6
   links:
     - db:db
   ports:
     - 18081:80
   environment:
     PMA_HOST: db
     PMA_USER: wordpress
     PMA_PASSWORD: wordpress
